### ISSUE TITLE
Genesis creation

### ISSUE THREAD

**Issue by zgreat** [xCoreDev/vcash#16]
Any details on the genesis creation process?

**Comment by augustresende** [comment]
I would also like to know

**Comment by zgreat** [comment]
I'll tip whoever is willing to share in bitcoin or ether

**Comment by xCoreDev** [comment]
Hi ! There's a dedicated funct to create the genesis: https://github.com/openvcash/vcash/blob/40cf07f439dd295b0a65c3290800cc3af1503940/coin/src/block.cpp#L316-L470
(I'm closing the issue, please reopen if needed)
