### ISSUE TITLE
[RPC] getbestblockhash

### ISSUE THREAD

**Issue by cryptokat** [xCoreDev/vcash#29]
plan to implement https://chainquery.com/bitcoin-api/getbestblockhash

**Comment by sum01** [comment]
Can't the same thing be achieved doing `getblockcount` and feeding its output into `getblockhash`?

**Comment by cryptokat** [comment]
@sum01 this is required for stratum solo-mining 
https://github.com/Crypto-Expert/stratum-mining/blob/master/lib/bitcoin_rpc.py#L149
