### ISSUE TITLE
Vcash fork issue

### ISSUE THREAD

**Issue by miningpoolhub** [xCoreDev/vcash#3]
Hi

I run two Vcash daemon from two servers now and found that Vcash:0.5.0 sometimes does not follow correct chain.
Vcash 0.4.7 is at the same height like block explorer
https://www.blockexperts.com/xvc

Vcash 0.5.0 was far behind the height and seemed like stuck at some point.
I restarted Vcash 0.5.0 and it did not move.

I reverted to last saved backup blockchain files and Vcash 0.4.7.
I think some consesus condition did not met at some point.

I have blockchain file still but don't have last ran log because it was automatically deleted when I restarted Vcash. Sorry for that.

**Comment by cryptopos** [comment]
If you run linux you need to update do the last Xcore version https://github.com/xCoreDev/vcash-scripts and, in any case, make sure your nodes are on the correct chain: https://explorer.vchain.info/network

**Comment by miningpoolhub** [comment]
Yeah I was running the latest xCoreDev's daemon. I updated daemon after jc left.

**Comment by miningpoolhub** [comment]
I think it is not a light problem. As there were some fork issue lately, this should be fixed before adding some fancy features.
I'm afraid to upgrade to latest version currently.

**Comment by pingofchaos** [comment]
Is this fixed or not?
