### ISSUE TITLE
How to set the rpc port&username for the vcash wallet?wane to  run a pool

### ISSUE THREAD

**Issue by chuanwc** [xCoreDev/vcash#35]
I want to run a pool for vcash but don't konw how to set the rpc port&rpcusername for the deamon.any help?in the config.dat file seems there is no place to set the rpcuser&password and i also don't know how to set rpcallowip like anyother daemons.any idea?

**Comment by bobfeldbauer** [comment]
There is no authentication on the RPC, so be careful. User is: "user", password is blank. Port is 9195 but can be set in the config.dat. To allow specific IPs, run the daemon with "--rpc-allow-ips=x.x.x.x" like: ./Vcashd --rpc-allow-ips=10.0.0.1,10.0.0.2

**Comment by chuanwc** [comment]
thank you so much
