### ISSUE TITLE
mining deposit and upgrade

### ISSUE THREAD

**Issue by man-FIRE** [xCoreDev/vcash#39]
Hi my friend, after more 24 hours and more 1TH of speed, we have nothing in my wallet and the explorer show nothing.

Please check and fix fastest possible else we going to stop mining vcash sorry.

VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U | 24120134 | 0 | 100% | 1.73 TH
https://pool.vchain.info/workers

-- | -- | -- | -- | --

I use 

Vcash-Electron-GUI-0.33.1-x86.exe
my port is open all seem good !

**Comment by man-FIRE** [comment]
VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U | 24120134 | 0 | 100% | 1.73 TH

-- | -- | -- | -- | --

I use 

Vcash-Electron-GUI-0.33.1-x86.exe
my port is open all seem good !

**Comment by man-FIRE** [comment]
[INFO] - coin::tcp_connection::send_getdata_message: TCP connection 2032841017 is sending getdata, count = 1, type = 2
[ERROR] - coin::kernel::check_proof_of_stake: Kernel, check proof of stake failed, read tx previous failed.
[ERROR] - errcall: Database environment, arg2 = BDB2580 DB_LOGC->get: LSN 165/6937804: invalid log record header.
[ERROR] - errcall: Database environment, arg2 = BDB2571 log file auto-remove: Input/output error.
[ERROR] - errcall: Database environment, arg2 = BDB2580 DB_LOGC->get: LSN 165/6937804: invalid log record header.
[ERROR] - errcall: Database environment, arg2 = BDB2571 log file auto-remove: Input/output error.
[INFO] - coin::tcp_connection::send_getdata_message: TCP connection 1730044560 is sending getdata, count = 1, type = 2
[ERROR] - errcall: Database environment, arg2 = BDB2580 DB_LOGC->get: LSN 165/6937804: invalid log record header.

**Comment by sum01** [comment]
Use https://pool.vcash.info/ instead. That other pool is behind in blocks for whatever reason.

**Comment by man-FIRE** [comment]
thx for your awnser bro I redirect all my stuff on the new adress, do you need some help ? I have more 20 years in background ddos migration and system linux admin + u-boot work, please juste let me know. Dont forget redirection 301 on your other pool, can you confirm how many hours for see the result on my wallet ? thx

**Comment by sum01** [comment]
It's not my pool, it's xCore's. I think the old one is just neglected.

Closing.

**Comment by man-FIRE** [comment]
I have allready new block mined
 Block: 885559 4 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
 Block: 885556 6 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
 Block: 885552 11 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
 Block: 866726 24 days ago

but I see more 30 dayts without confirmation ... when I am going to be pay ?

**Comment by sum01** [comment]
Unless I am mistaken, payment should go out after 220 confirmations on the block.

**Comment by man-FIRE** [comment]
new thrend https://github.com/openvcash/vcash/issues/40
