### ISSUE TITLE
New pool new block mined no confirmation 

### ISSUE THREAD

**Issue by man-FIRE** [xCoreDev/vcash#40]
I have allready new block mined
Block: 885559 4 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
Block: 885556 6 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
Block: 885552 11 minutes ago Pending
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U
Block: 866726 24 days ago

but I see more 30 dayts without confirmation ... when I am going to be pay ?
hen I am going to be pay ?

**Comment by man-FIRE** [comment]
It possible for me to auto confirme the 220 ?  do you think is better to use linux wallet my windows wallet look  like jamed on the old block

**Comment by sum01** [comment]
I already said that it's likely (I don't run the pool so I don't know the actual setting) that it'll be payed out at 220 confirmations, as per the old pool.

I don't know what you mean by auto-confirm. 220 confirmations means that it has been included in 220 blocks mined by people, thus "confirming" the blocks legitimacy.

**Comment by man-FIRE** [comment]
if I want to be pay now is better to make solo pool ?

**Comment by sum01** [comment]
Yeah I guess so. I've never run one, but I assume you can adjust the payout confirmation number.

**Comment by man-FIRE** [comment]
I understant bro if not your money or pool but without that no interest for vcash do you have a solo mining tutorial for setup on linux I going to try to setup one

**Comment by sum01** [comment]
Solo-mining requires you setup your own pool, just don't make it public. It's not like some coins where you just point at an address on your LAN.

See here https://github.com/openvcash/vcash/issues/36 for discussion on setting up a pool.

**Comment by man-FIRE** [comment]
lol bro, I see confirmation allready 
https://explorer.vcash.info/block/0000000000001014907eb1a0997a757f3104cefc0e5e8862c937f8adf311e1ae

the problem is only the node for mining say no confirmation !

**Comment by sum01** [comment]
I guess there's something wrong with the software displaying the confirmations. I have no control over it, so nothing I can do sadly.

**Comment by man-FIRE** [comment]
the only problem is I see on my windows wallet 

the block  852 775

852 775
96,3%
settings_input_antenna
4 TCP • 19 UDP
cast_connected


it possible to see the real new block so 885552 ?

**Comment by sum01** [comment]
> 96.3%

That means your wallet isn't fully synced to the blockchain yet. You'll see the new blocks when it finishes downloading the rest of the blockchain.

**Comment by man-FIRE** [comment]
why I never move 96% after 24 hours ? I going to try dmz or repair somefile or if I use coinomie is better ?

**Comment by sum01** [comment]
I would just restart your wallet then. Probably something out of whack with your network.

**Comment by man-FIRE** [comment]
Incentive manager wallet is locked, will try again. ?

**Comment by man-FIRE** [comment]
coin::database_stack::tick: Database stack has 133 UDP connections.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1089903788 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1970946856 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1089903788 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1970946856 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1089903788 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1970946856 is sending getblocks.
[INFO] - coin::tcp_connection::do_send_getblocks: TCP connection 1089903788 is sending getblocks. 

I just neewd to wait now ?

**Comment by man-FIRE** [comment]
give me some right for update some  ip pool etc in the github for help you thx !

**Comment by sum01** [comment]
> Incentive manager wallet is locked, will try again. ?

That means you have proof-of-stake enabled in your `config.dat`, but the wallet is locked so it can't actually stake your coins. Either close the wallet, turn PoS to `0` in the config, or unlock your wallet to stake the coins.

> give me some right for update some ip pool etc in the github for help you thx !

Not sure what you're trying to say.
