### ISSUE TITLE
48 hours of mining 1TH vcash  17 XVC ???

### ISSUE THREAD

**Issue by man-FIRE** [xCoreDev/vcash#41]
https://explorer.vcash.info/address/VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U

sir what the problem sir, with your calcul we suppost to mine and receive more 6000us for 2 day

and  I have only 17 XVC ????

**Comment by sum01** [comment]
I doubt you'll get anything for your time mining on the old pool (vchain.info) since it was behind in blocks. I'm guessing the 17 is from since you moved to the new pool (vcash.info).

**Comment by man-FIRE** [comment]
i have mine 24h old one and 24h on the new one, i have moved my miner please fix and  i come back thx you

**Comment by sum01** [comment]
I've said in the previous issues that I have no control over either pool. There's nothing I can do.

**Comment by man-FIRE** [comment]
What next dude ? is possible to mine with only vcashd setup on linux or not ?

**Comment by sum01** [comment]
Already answered https://github.com/openvcash/vcash/issues/40#issuecomment-359187443

If you have more general questions, please ask in the Slack instead. https://slack.vcash.info/

**Comment by man-FIRE** [comment]
slack invitation is blocked limited

**Comment by man-FIRE** [comment]
这是我关于区块链冷冻货币的最后一个警告，你没有时间来解决这个问题，或者你将从bittrex去除。

**Comment by sum01** [comment]
> slack invitation is blocked limited

Just started a [Gitter room](https://gitter.im/openvcash/vcash?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for chatting.
