### ISSUE TITLE
block mined by me - another person get pay - you need to fix that 

### ISSUE THREAD

**Issue by man-FIRE** [xCoreDev/vcash#45]
Block mined with your pool ( https://pool.vcash.info/ ) , more 200+ confirmation

 Block: 888392

 Wed Jan 24 2018 13:01:36 GMT+0100 (CET) Pending 
Mined By: VkD8MY4tFYh33ANGRPfGzru5FGRvYHbs7U

Bblock  888392
https://explorer.vcash.info/block/0000000000002c6c8ba6ce21b822cae11020707cabfafdc6825101d060adb369

2 other wallet get pay for each mining block ... this is a fraud....

we need explain and you need to fix the situation.

**Comment by whphhg** [comment]
I'm not a miner, but the https://pool.vcash.info is @xCoreDev's testing pool for the `z-nomp` pool management software and I believe is not meant to be mined on. As far as I know the correct pool to use is the one on the website, https://pool.vchain.info which uses the `nomp` software.

It would be better if a miner or someone with more knowledge than me could help you.

**Comment by man-FIRE** [comment]
same https://pool.vchain.info  mined 2 day and no result my friend

**Comment by man-FIRE** [comment]
182.127.98.18 | 0 |   | China
-- | -- | -- | --
182.116.38.171 | 0 |   | China
222.141.127.220 | 0 |   | China
123.12.224.123 | 0 |   | China
182.116.35.22 | 0 |   | China
42.232.237.99 | 0 |   | China
42.226.73.208 | 0 |   | China
182.112.33.20 | 0 |   | China
182.112.45.32 | 0 |   | China
182.127.69.196 | 0 |   | China

**Comment by sum01** [comment]
Perhaps you were generating a lot of invalid shares from misconfigured settings?

And what are the IP's supposed to be for?

**Comment by man-FIRE** [comment]
dont try to give any bad reason a generating a very tiny tiny invalid share,  your misconfigured settings like url + wallet and start mining. you dont need my ip adress, you vcash wallet money and mine result is corrumped. You have 72 hours for fixe the issue. I allready put your wallet in "maintenance mode" on bittrex this is my last warning, next time your going to be complete removed.

**Comment by sum01** [comment]
I removed those pools removed from the wiki, but I have no control over those pools, and cannot make random payments to people who mined on a bad pool. Sorry if you lost coins, but I suggest you stop mining on it if it isn't paying out.

I've uploaded a [guide to running your own pool](https://github.com/openvcash/vcash/wiki/Running-A-Pool) on the wiki if you still wish to mine.
