### ISSUE TITLE
Copyrights edit

### ISSUE THREAD

**Issue by xCoreDev** [xCoreDev/vcash#5]
Hi, a quick issue to talk about the src files Copyrights.
To sum, it's a rewrite of the ppcoin codebase by JC. So there's:
- the PoW part related to bitcoin
- the PoS part related to ppcoin
- JC's improvements based on his previous projects (codebase structure, UDP layer), and new features like the ZeroTime off-chain confirmation voting&locking system, or the ChainBlender client-side mixing system

The question is should we replace current "This file is part of vcash." headers with a general header like:
```
/*
 * Copyright (c) 2009-2010 Satoshi Nakamoto
 * Copyright (c) 2009-2012 The Bitcoin developers
 * Copyright (c) 2011-2015 The Peercoin developers
 * Copyright (c) 2013-2016 John Connor
 * Copyright (c) 2016-2017 The Vcash developers
 *
 * This file is part of vcash.
 *
 * vcash is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License with
 * additional permissions to the one published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version. For more information see LICENSE.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
```

or should we make a custom one depending which funct are present in the files: bitcoin and/or ppcoin and/or vcash ?

**Comment by whphhg** [comment]
General header seems like the best way to go as it gives proper credit to everyone involved. The version you provided looks solid.

**Comment by xCoreDev** [comment]
@bitspill from slack:

> While on the topic of rights, I don't think vcash can be GNU Affero GPL, since the original base was MIT
> But, IANAL so perhaps MIT allows you to relicense derivative works

Maybe the best would be to see for a License switch from GPLv3 to the more permissive MIT ?
All previous contributors must be ok w/ the LICENSE changes from what I read. But how to do that if one or more contributors stay silent ?
We need a LICENSE expert to help us to solve that issue.

**Comment by maccaspacca** [comment]
(My opinion and understanding only)

Any software under this repository is a fork of the original John Conner code and is considered a new modified version of the original therefore a new or updated license must be distributed when it is published. You must comply with the terms of the licenses for any software used to contribute to the modified software.

If you feel that bitcoin and peercoin were not correctly acknowledged in the John Conner code then you should add the acknowledgements as required by their license terms (e.g. MIT)

As the John Conner software was published under GNU Affero then the new modified version should be distributed with the same license (this is part of the license terms)

In essence the general form is good (it will need amending) as you will have effectively created a modified version of the software when you release your new code and distribute it. Both the GNU Affero and MIT licenses already give permission to create modified versions of the software without the need to contact or get further permission - providing full acknowledgement is given. As there are two separate types of license being applied then you will need to have a separate statement for each type. I would have an MIT license statement in respect of bitcoin and peercoin but publish under GNU Affero for John Conner and your new  or modified components.

You already have a license file for the GNU Affero but you should also add a license file for the MIT components (e.g. from the peercoin repository?) amended to explain which components are MIT.

The main point of the law is that you attempt to fulfill the requirements of the relevant licenses as best you can and it is for the original copyright owners to tell you where you are not compliant and allow you to remedy the situation once this has been pointed out e.g. with additional acknowledgements etc.

**Comment by xCoreDev** [comment]
Let's stick with a general GPLv3, at least is a good start. We will see later if it needs more clarification.
I keep the issue opened atm.
Thx all for your answers.

**Comment by xCoreDev** [comment]
I started with that header:
```
/*
 * Copyright (c) 2013-2016 John Connor
 * Copyright (c) 2016-2017 The Vcash developers
 *
 * This file is part of vcash.
 *
 * vcash is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License with
 * additional permissions to the one published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version. For more information see LICENSE.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
```
I will put a notice regarding Peercoin & Bitcoin in the README file.
I close the issue for now, but this subject is still open if someone can provide more clarification / concrete examples.
